{% set name = "perl-try-tiny" %}
{% set version = "0.32" %}
{% set sha256 = "ef2d6cab0bad18e3ab1c4e6125cc5f695c7e459899f512451c8fa3ef83fa7fc0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/E/ET/ETHER/Try-Tiny-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  # perl-capture-tiny has no win build
  skip: true  # [win]
  run_exports:
    weak:
      - {{ name }} ={{ version }}

requirements:
  build:
    - make
  host:
    - perl
    - perl-capture-tiny
  run:
    - perl

test:
  imports:
    - Try::Tiny

about:
  home: https://github.com/p5sagit/Try-Tiny
  license: MIT
  summary: 'Minimal try/catch with proper preservation of $@'
  license_family: MIT
  license_file: LICENCE

extra:
  recipe-maintainers:
    - dslarm
    - xileF1337
